### ISSUE TITLE
Runtime of CircleCI jobs exceed the limit for the free tier

### ISSUE THREAD

**Issue by geedo0** [open-quantum-safe/openssh-portable#166]
CircleCI's free tier limits a job's run time to 1 hour [doc](https://circleci.com/docs/configuration-reference/#jobs). The CI checks run by OpenSSH have been approaching that 1 hour limit and are now at the point where they just barely run past that limit and fail the CI checks [example](https://app.circleci.com/pipelines/github/open-quantum-safe/openssh/1012/workflows/891ff34b-8cea-4fc5-9b65-452196ae1cd6/jobs/4235?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary). Previous runs were already pretty close to the limit, the addition of new algorithms to test was enough to tip the run-time over the limit.

There's no solution that doesn't come with trade-offs, but here are some possibilities:
- Migrate to a new CI framework like Github Actions. This seems to be the right choice, but I don't have the context on why CircleCI was chosen in the first place.
- Upgrade to the paid Performance Plan [pricing](https://circleci.com/pricing/).
- Audit the unit tests and skip tests that have long running times and aren't particularly interesting for OQS.
- Look into refactoring the tests into parallel jobs that fit within the limits.

**Comment by geedo0** [comment]
@SWilson4 Here's that CircleCI issue I mentioned. I've got a first pass at porting it to Github Actions here. However, there's some difference in how the container/host handles process reaping which breaks a unit test, but I can patch around that.

```
name: CI Checks
on: [ push, pull_request ]
jobs:
  ubuntu_build:
    runs-on: ubuntu-latest
    container:
      image: openquantumsafe/ci-ubuntu-focal-x86_64:latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up SSH environment
      run: |
        mkdir -p -m 0755 /var/empty
        groupadd sshd
        useradd -g sshd -c 'sshd privsep' -d /var/empty -s /bin/false sshd
    - name: Clone liboqs
      run: ./oqs-scripts/clone_liboqs.sh
    - name: Build liboqs
      run: ./oqs-scripts/build_liboqs.sh
    - name: Build OpenSSH
      run: env WITH_OPENSSL=true ./oqs-scripts/build_openssh.sh
    - name: Run tests documented to pass
      run: ./oqs-test/run_tests.sh
    - name: Ensure we have the ssh and sshd syntax right once for each algorithm
      run: python3 oqs-test/try_connection.py doone
```
